import { auditResources } from './resource.config.audit';
import {
  artifactsCreateFields,
  reasonCodesCreateFields,
  variablesCreateFields,
  variablesCreateStaticBody,
} from './resource.create-fields';
import type { ResourceConfig } from './resource.types';

/** Enum values whose code is already a readable label. */
const opts = (...values: string[]) => values.map((value) => ({ value, label: value }));

export const resources: Readonly<Record<string, ResourceConfig>> = {
  variables: {
    key: 'variables',
    eyebrow: 'F1-01 · Catálogo',
    title: 'Variable Catalog',
    description: 'Definiciones versionadas utilizadas por reglas, modelos y decisiones.',
    hint: 'Catálogo de los datos (edad, ingreso, score…) que tus decisiones pueden usar. Cada variable tiene un código estable, un tipo y una versión.',
    endpoint: '/v1/variables',
    // El detalle abre el contrato completo: restricciones, ejemplos, versiones y quién
    // usa la variable. Sin él, el catálogo solo dejaba ver el resumen de una fila.
    detailPath: (row) => `/variables/${String(row.id ?? '')}`,
    filterParam: 'search',
    filterLabel: 'Buscar variables',
    filterPlaceholder: 'Código o nombre',
    primaryAction: 'Add Variable',
    createFields: variablesCreateFields,
    createStaticBody: variablesCreateStaticBody,
    filters: [
      {
        param: 'usage',
        label: 'Entrada / Salida',
        options: [
          { value: 'INPUT', label: 'Entradas (datos que se aportan)' },
          { value: 'OUTPUT', label: 'Salidas (resultados que devuelve)' },
        ],
        placeholder: 'Cualquier sentido',
      },
    ],
    columns: [
      { key: 'variableCode', label: 'Code', mono: true },
      { key: 'name', label: 'Name' },
      {
        key: 'usage',
        label: 'Uso',
        status: true,
        hint: 'Si los algoritmos la usan como ENTRADA (dato que hay que aportar) o como SALIDA (resultado que el motor produce).',
      },
      { key: 'category', label: 'Category' },
      {
        key: 'dataType',
        label: 'Data Type',
        hint: 'El tipo de dato: número, texto, booleano, fecha…',
      },
      { key: 'source', label: 'Source' },
      { key: 'latestVersion', label: 'Version' },
      {
        key: 'sensitivity',
        label: 'Sensitivity',
        status: true,
        hint: 'Si el dato es sensible (PII) y el motor debe tratarlo con controles reforzados.',
      },
      { key: 'status', label: 'Status', status: true },
      { key: 'updatedAt', label: 'Updated' },
    ],
  },
  'reason-codes': {
    key: 'reason-codes',
    eyebrow: 'F1-06 · Catálogo',
    title: 'Reason Codes Catalog',
    description: 'Códigos explicables para resultados de crédito, fraude y cumplimiento.',
    hint: 'Los motivos explicables que acompañan cada decisión (por qué se aprobó o rechazó). Son la base de la transparencia y de los avisos legales de decisión adversa.',
    endpoint: '/v1/reason-codes',
    filterParam: 'search',
    filterLabel: 'Buscar reason code',
    filterPlaceholder: 'Código, título o mensaje',
    primaryAction: 'Add Reason Code',
    createFields: reasonCodesCreateFields,
    filters: [
      {
        param: 'category',
        label: 'Categoría',
        optionsEndpoint: '/v1/views/options?group=reasonCategory',
        placeholder: 'Categoría exacta',
      },
    ],
    columns: [
      { key: 'reasonCode', label: 'Code', mono: true },
      { key: 'category', label: 'Category' },
      { key: 'severity', label: 'Severity', status: true },
      {
        key: 'publicMessage',
        label: 'Mensaje público',
        hint: 'El mensaje explicable que ve el cliente cuando este motivo acompaña una decisión.',
      },
      { key: 'internalMessage', label: 'Mensaje interno' },
      { key: 'isActive', label: 'Status', status: true },
    ],
  },
  artifacts: {
    key: 'artifacts',
    eyebrow: 'F2-01 · Diseño',
    title: 'Inventario de Artefactos',
    description: 'Manage and monitor all decision artifacts in the system.',
    hint: 'Un artefacto es un algoritmo de decisión versionable: su grafo, sus reglas y su contrato de entradas/salidas. Aquí ves y creas todos los del sistema.',
    endpoint: '/v1/artifacts',
    filterParam: 'search',
    filterLabel: 'Buscar artefacto',
    filterPlaceholder: 'Código, nombre o equipo',
    primaryAction: 'Nuevo Artefacto',
    createFields: artifactsCreateFields,
    filters: [
      {
        param: 'status',
        label: 'Estado',
        options: opts(
          'DRAFT',
          'VALIDATION_FAILED',
          'VALIDATED',
          'COMPILED',
          'IN_REVIEW',
          'CHANGES_REQUESTED',
          'APPROVED',
          'DEPLOYED_TO_SANDBOX',
          'DEPLOYED_TO_TEST',
          'DEPLOYED_TO_PROD',
          'SUSPENDED',
          'REJECTED',
          'RETIRED',
        ),
      },
    ],
    detailPath: (row) => `/artifacts/${String(row.id)}`,
    columns: [
      { key: 'artifactCode', label: 'Code', mono: true },
      { key: 'name', label: 'Name' },
      { key: 'artifactType', label: 'Type' },
      { key: 'ownerTeam', label: 'Owner Team' },
      { key: 'latestVersion', label: 'Version' },
      { key: 'latestStatus', label: 'Status', status: true },
      { key: 'environmentCode', label: 'Environment' },
      { key: 'lastValidatedAt', label: 'Last Val' },
    ],
  },
  reviews: {
    key: 'reviews',
    eyebrow: 'F4-01 · Gobierno',
    title: 'Bandeja de Revisiones',
    description: 'Solicitudes de aprobación pendientes para Quality, Riesgo y Compliance.',
    hint: 'Solicitudes de aprobación que deben resolverse antes de que una versión de un algoritmo pueda desplegarse.',
    endpoint: '/v1/approval-requests',
    detailPath: (row) => `/approval-requests/${String(row.id)}`,
    columns: [
      { key: 'artifactCode', label: 'Artefacto', mono: true },
      { key: 'versionNumber', label: 'Versión' },
      { key: 'workflowCode', label: 'Tipo' },
      { key: 'requestedBy', label: 'Solicitante' },
      {
        key: 'currentStep',
        label: 'Paso Actual',
        hint: 'En qué paso del flujo de aprobación (Quality, Riesgo, Compliance…) está la solicitud.',
      },
      {
        key: 'slaStatus',
        label: 'SLA',
        status: true,
        hint: 'Si la revisión va dentro del plazo acordado (SLA) o ya lo incumplió.',
      },
      { key: 'createdAt', label: 'Fecha' },
    ],
  },
  deployments: {
    key: 'deployments',
    eyebrow: 'F4-07 · Gobierno',
    title: 'Historial de Despliegues',
    description: 'Registro auditable de promociones, resultados y rollbacks por ambiente.',
    hint: 'Registro de cuándo y a qué ambiente (sandbox, test, producción) se publicó cada versión de un algoritmo, y de las reversiones (rollbacks).',
    endpoint: '/v1/deployments',
    filterParam: 'artifactCode',
    filterLabel: 'Buscar artefacto',
    filterPlaceholder: 'Código exacto',
    primaryAction: 'Nuevo Despliegue',
    filters: [
      { param: 'environmentCode', label: 'Ambiente', placeholder: 'p. ej. PROD' },
      {
        param: 'status',
        label: 'Resultado',
        options: opts('PREPARING', 'ACTIVE', 'SUSPENDED', 'SUPERSEDED', 'ROLLED_BACK', 'FAILED'),
      },
    ],
    columns: [
      {
        key: 'artifactCode',
        label: 'Artefacto',
        mono: true,
        path: 'artifactVersion.artifact.artifactCode',
      },
      { key: 'versionNumber', label: 'Versión', path: 'artifactVersion.versionNumber' },
      {
        key: 'deploymentMode',
        label: 'Modo',
        hint: 'Cómo se publicó: directo, canary (gradual) o sombra (shadow, sin afectar decisiones reales).',
      },
      { key: 'environmentCode', label: 'Ambiente', path: 'environment.code' },
      { key: 'deployedBy', label: 'Desplegado por' },
      { key: 'deployedAt', label: 'Fecha' },
      {
        key: 'deploymentStatus',
        label: 'Resultado',
        status: true,
        hint: 'Estado del despliegue: activo, suspendido, reemplazado o revertido.',
      },
    ],
  },
  'manual-reviews': {
    key: 'manual-reviews',
    eyebrow: 'F5-03 · Operación',
    title: 'Cola de Revisión Manual',
    description: 'Casos derivados por reglas que requieren una decisión humana controlada.',
    hint: 'Casos que el algoritmo no decidió automáticamente y derivó a una persona para resolverlos manualmente.',
    endpoint: '/v1/manual-reviews',
    filterParam: 'queueCode',
    filterLabel: 'Buscar caso',
    filterPlaceholder: 'Case ID o referencia',
    filters: [
      {
        param: 'status',
        label: 'Estado',
        options: opts('OPEN', 'ASSIGNED', 'RESOLVED_APPROVED', 'RESOLVED_DECLINED', 'CANCELLED'),
      },
      { param: 'assignedTo', label: 'Asignado a', placeholder: 'Usuario' },
    ],
    detailPath: (row) => `/manual-reviews/${String(row.id)}`,
    columns: [
      { key: 'caseCode', label: 'Case ID', mono: true },
      {
        key: 'priority',
        label: 'Prioridad',
        hint: 'Qué tan urgente es el caso respecto de los demás de la cola.',
      },
      { key: 'queueCode', label: 'Cola', mono: true },
      { key: 'requestId', label: 'Ejecución', mono: true, path: 'execution.requestId' },
      {
        key: 'businessOutcome',
        label: 'Outcome',
        status: true,
        path: 'execution.businessOutcome',
        hint: 'El resultado de negocio de la decisión original (p. ej. APROBADO, RECHAZADO, DERIVADO).',
      },
      { key: 'assignedTo', label: 'Asignado a' },
      {
        key: 'dueAt',
        label: 'SLA (vence)',
        hint: 'Fecha límite para resolver el caso antes de incumplir el acuerdo de nivel de servicio (SLA).',
      },
    ],
  },
  ...auditResources,
};
