import type { ResourceConfig } from './resource.types';

export const resources: Readonly<Record<string, ResourceConfig>> = {
  variables: {
    key: 'variables',
    eyebrow: 'F1-01 · Catálogo',
    title: 'Variable Catalog',
    description: 'Definiciones versionadas utilizadas por reglas, modelos y decisiones.',
    endpoint: '/v1/variables',
    filterParam: 'search',
    filterLabel: 'Buscar variables',
    filterPlaceholder: 'Código o nombre',
    primaryAction: 'Add Variable',
    staticFilters: ['Categoría', 'Tipo de dato', 'Sensibilidad'],
    columns: [
      { key: 'variableCode', label: 'Code', mono: true },
      { key: 'name', label: 'Name' },
      { key: 'category', label: 'Category' },
      { key: 'dataType', label: 'Data Type' },
      { key: 'source', label: 'Source' },
      { key: 'latestVersion', label: 'Version' },
      { key: 'sensitivity', label: 'Sensitivity', status: true },
      { key: 'status', label: 'Status', status: true },
      { key: 'updatedAt', label: 'Updated' },
    ],
  },
  'reason-codes': {
    key: 'reason-codes',
    eyebrow: 'F1-06 · Catálogo',
    title: 'Reason Codes Catalog',
    description: 'Códigos explicables para resultados de crédito, fraude y cumplimiento.',
    endpoint: '/v1/reason-codes',
    filterParam: 'search',
    filterLabel: 'Buscar reason code',
    filterPlaceholder: 'Código, título o mensaje',
    primaryAction: 'Add Reason Code',
    staticFilters: ['Categoría', 'Severidad'],
    columns: [
      { key: 'code', label: 'Code', mono: true },
      { key: 'category', label: 'Category' },
      { key: 'severity', label: 'Severity', status: true },
      { key: 'title', label: 'Title' },
      { key: 'internalMessage', label: 'Internal Message' },
      { key: 'isActive', label: 'Status', status: true },
    ],
  },
  artifacts: {
    key: 'artifacts',
    eyebrow: 'F2-01 · Diseño',
    title: 'Inventario de Artefactos',
    description: 'Manage and monitor all decision artifacts in the system.',
    endpoint: '/v1/artifacts',
    filterParam: 'search',
    filterLabel: 'Buscar artefacto',
    filterPlaceholder: 'Código, nombre o equipo',
    primaryAction: 'Nuevo Artefacto',
    staticFilters: ['Tipo', 'Estado', 'Ambiente'],
    detailPath: (row) => `/artifacts/${String(row.id)}`,
    columns: [
      { key: 'artifactCode', label: 'Code', mono: true },
      { key: 'name', label: 'Name' },
      { key: 'artifactType', label: 'Type' },
      { key: 'ownerTeam', label: 'Owner Team' },
      { key: 'latestVersion', label: 'Version' },
      { key: 'latestStatus', label: 'Status', status: true },
      { key: 'environmentCode', label: 'Environment' },
      { key: 'lastValidatedAt', label: 'Last Val' },
    ],
  },
  reviews: {
    key: 'reviews',
    eyebrow: 'F4-01 · Gobierno',
    title: 'Bandeja de Revisiones',
    description: 'Solicitudes de aprobación pendientes para Quality, Riesgo y Compliance.',
    endpoint: '/v1/approval-requests',
    filterParam: 'status',
    filterLabel: 'Buscar solicitud',
    filterPlaceholder: 'Artefacto o solicitante',
    staticFilters: ['Tipo de revisión', 'Paso actual', 'SLA'],
    detailPath: (row) => `/approval-requests/${String(row.id)}`,
    columns: [
      { key: 'artifactCode', label: 'Artefacto', mono: true },
      { key: 'versionNumber', label: 'Versión' },
      { key: 'workflowCode', label: 'Tipo' },
      { key: 'requestedBy', label: 'Solicitante' },
      { key: 'currentStep', label: 'Paso Actual' },
      { key: 'slaStatus', label: 'SLA', status: true },
      { key: 'createdAt', label: 'Fecha' },
    ],
  },
  deployments: {
    key: 'deployments',
    eyebrow: 'F4-07 · Gobierno',
    title: 'Historial de Despliegues',
    description: 'Registro auditable de promociones, resultados y rollbacks por ambiente.',
    endpoint: '/v1/deployments',
    filterParam: 'artifactCode',
    filterLabel: 'Buscar artefacto',
    filterPlaceholder: 'Código exacto',
    primaryAction: 'Nuevo Despliegue',
    staticFilters: ['Ambiente', 'Resultado', 'Fecha'],
    columns: [
      { key: 'artifactCode', label: 'Artefacto', mono: true },
      { key: 'versionNumber', label: 'Versión' },
      { key: 'checksum', label: 'Checksum', mono: true },
      { key: 'environmentCode', label: 'Ambiente' },
      { key: 'deployedBy', label: 'Desplegado por' },
      { key: 'deployedAt', label: 'Fecha' },
      { key: 'status', label: 'Resultado', status: true },
    ],
  },
  'manual-reviews': {
    key: 'manual-reviews',
    eyebrow: 'F5-03 · Operación',
    title: 'Cola de Revisión Manual',
    description: 'Casos derivados por reglas que requieren una decisión humana controlada.',
    endpoint: '/v1/manual-reviews',
    filterParam: 'queueCode',
    filterLabel: 'Buscar caso',
    filterPlaceholder: 'Case ID o referencia',
    staticFilters: ['Prioridad', 'Asignación', 'SLA'],
    detailPath: (row) => `/manual-reviews/${String(row.id)}`,
    columns: [
      { key: 'id', label: 'Case ID', mono: true },
      { key: 'priority', label: 'Priority', status: true },
      { key: 'reason', label: 'Reason' },
      { key: 'artifactCode', label: 'Artifact', mono: true },
      { key: 'subjectReference', label: 'Customer Ref (Masked)', mono: true },
      { key: 'assignedTo', label: 'Assigned To' },
      { key: 'slaDueAt', label: 'Age (SLA)', status: true },
    ],
  },
  executions: {
    key: 'executions',
    eyebrow: 'F6-01 · Auditoría',
    title: 'Buscador de Ejecuciones',
    description: 'Consulta reproducible de solicitudes, resultados, tiempos y trazas.',
    endpoint: '/v1/audit/executions',
    filterParam: 'artifactCode',
    filterLabel: 'Request ID / Artefacto',
    filterPlaceholder: 'req_... o código',
    staticFilters: ['Ambiente', 'Outcome', 'Rango de fecha'],
    detailPath: (row) => `/executions/${String(row.id)}`,
    columns: [
      { key: 'createdAt', label: 'Fecha / Hora' },
      { key: 'requestId', label: 'Request ID', mono: true },
      { key: 'artifactCode', label: 'Artefacto / Versión', mono: true },
      { key: 'environmentCode', label: 'Ambiente' },
      { key: 'outcome', label: 'Outcome', status: true },
      { key: 'durationMs', label: 'Duración (ms)' },
    ],
  },
  'audit-events': {
    key: 'audit-events',
    eyebrow: 'F6-05 · Auditoría',
    title: 'Bitácora de Auditoría',
    description: 'Cadena inmutable de eventos administrativos y operativos.',
    endpoint: '/v1/audit/events',
    filterParam: 'eventType',
    filterLabel: 'Buscar evento',
    filterPlaceholder: 'Evento, actor o IP',
    staticFilters: ['Evento', 'Actor', 'Fecha'],
    columns: [
      { key: 'createdAt', label: 'Fecha / Hora' },
      { key: 'eventType', label: 'Evento', mono: true },
      { key: 'actorId', label: 'Actor', mono: true },
      { key: 'ipAddress', label: 'IP Origen', mono: true },
      { key: 'previousHash', label: 'Hash Anterior', mono: true },
      { key: 'currentHash', label: 'Hash Actual', mono: true },
    ],
  },
  objectives: {
    key: 'objectives',
    eyebrow: 'F7-01 · Business Traceability',
    title: 'Objetivos de Negocio',
    description: 'Métricas, políticas, artefactos y pruebas conectados de extremo a extremo.',
    endpoint: '/v1/traceability/objectives',
    filterParam: 'search',
    filterLabel: 'Buscar objetivo',
    filterPlaceholder: 'Código, nombre o propietario',
    primaryAction: 'Nuevo Objetivo',
    staticFilters: ['Estado', 'Propietario'],
    detailPath: (row) => `/objectives/${String(row.id)}`,
    columns: [
      { key: 'objectiveCode', label: 'Código', mono: true },
      { key: 'name', label: 'Objetivo' },
      { key: 'metric', label: 'Métrica / Meta' },
      { key: 'ownerTeam', label: 'Propietario' },
      { key: 'policyCount', label: 'Políticas' },
      { key: 'artifactCount', label: 'Artefactos' },
      { key: 'testCount', label: 'Pruebas' },
      { key: 'status', label: 'Estado', status: true },
    ],
  },
};
