/**
 * Cómo se dice en pantalla cada estado que devuelve el motor.
 *
 * `StatusBadge` enseñaba el valor crudo en mayúsculas (ACTIVE, DRAFT, PASSED, WAITING…) salvo en
 * las 5 de sus 43 llamadas que pasaban su propio mapa. Éste es el mapa por defecto: una llamada con
 * `labels` propios sigue mandando, y un valor que no esté aquí se enseña legible (sin guiones
 * bajos, sólo la primera en mayúscula) en vez de como constante.
 */
export const STATUS_LABELS: Readonly<Record<string, string>> = {
  ACTIVE: 'Activo',
  INACTIVE: 'Inactivo',
  TRUE: 'Activo',
  FALSE: 'Inactivo',
  DRAFT: 'Borrador',
  DRAFT_SAVED: 'Borrador guardado',
  REVIEW: 'En revisión',
  IN_REVIEW: 'En revisión',
  PENDING: 'Pendiente',
  PENDING_REVIEW: 'Pendiente de revisión',
  WAITING: 'En espera',
  QUEUED: 'En cola',
  RUNNING: 'En curso',
  PROCESSING: 'Procesando',
  PREPARING: 'Preparando',
  GENERATING: 'Generando',
  READY: 'Listo',
  OPEN: 'Abierto',
  ASSIGNED: 'Asignado',
  RECEIVED: 'Recibido',
  REQUESTED: 'Solicitado',
  COMPLETED: 'Completado',
  COMPLETE: 'Completo',
  PARTIAL: 'Parcial',
  FULFILLED: 'Atendido',
  CONFIRMED: 'Confirmado',
  VALID: 'Válido',
  VALIDATED: 'Validado',
  INVALID: 'No válido',
  VALIDATION_FAILED: 'Falló la validación',
  COMPILED: 'Compilado',
  PUBLISHED: 'Publicado',
  DEPLOYED: 'Desplegado',
  DEPLOYED_TO_DEV: 'Desplegado en desarrollo',
  DEPLOYED_TO_TEST: 'Desplegado en pruebas',
  DEPLOYED_TO_STAGING: 'Desplegado en preproducción',
  DEPLOYED_TO_PROD: 'Desplegado en producción',
  ACTIVE_IN_ENVIRONMENT: 'Activo en el ambiente',
  SUPERSEDED: 'Reemplazado',
  ROLLED_BACK: 'Revertido',
  RETIRED: 'Retirado',
  DEPRECATED: 'En desuso',
  SUSPENDED: 'Suspendido',
  REVOKED: 'Revocado',
  BLOCKED: 'Bloqueado',
  CANCELLED: 'Cancelado',
  APPROVE: 'Aprobar',
  APPROVED: 'Aprobado',
  REJECT: 'Rechazar',
  REJECTED: 'Rechazado',
  DECLINED: 'Rechazado',
  CHANGES_REQUESTED: 'Cambios pedidos',
  REQUEST_CHANGES: 'Pedir cambios',
  MANUAL_REVIEW: 'Revisión manual',
  REVISION_MANUAL: 'Revisión manual',
  RESOLVED_APPROVED: 'Resuelto: aprobado',
  RESOLVED_DECLINED: 'Resuelto: rechazado',
  NO_DECISION: 'Sin decisión',
  PASS: 'Correcto',
  PASSED: 'Superada',
  FAIL: 'Falló',
  FAILED: 'Falló',
  FAILED_RETRYABLE: 'Falló (se reintentará)',
  FAILED_PERMANENT: 'Falló',
  SUCCESS: 'Correcto',
  SUCCEEDED: 'Correcto',
  SUCCEEDED_WITH_WARNINGS: 'Correcto con avisos',
  SKIP: 'Omitido',
  SKIPPED: 'Omitido',
  ERROR: 'Error',
  TIMEOUT: 'Tiempo agotado',
  WARN: 'Aviso',
  WARNING: 'Aviso',
  INFO: 'Informativo',
  OK: 'Correcto',
  HEALTHY: 'Funcionando',
  DEGRADED: 'Con fallas',
  DOWN: 'Caído',
  CRITICAL: 'Crítico',
  HIGH: 'Alto',
  MEDIUM: 'Medio',
  LOW: 'Bajo',
  BLOCKING: 'Obligatoria',
  NON_BLOCKING: 'Informativa',
  REQUIRED: 'Obligatorio',
  NONE: 'Ninguno',
  NOT_APPLICABLE: 'No aplica',
  PUBLIC: 'Público',
  INTERNAL: 'Interno',
  CONFIDENTIAL: 'Confidencial',
  RESTRICTED: 'Restringido',
  SECRET: 'Secreto',
  PII: 'Dato personal',
  SENSITIVE_PII: 'Dato personal sensible',
  INPUT: 'Entrada',
  OUTPUT: 'Salida',
  OUTPUT_PRIMARY: 'Salida principal',
  DIRECT: 'Completa',
  CANARY: 'Gradual',
  CHAMPION_CHALLENGER: 'Comparativa',
  WATCH: 'En observación',
  BREACH: 'Límite superado',
  EARLY_WARNING: 'Alerta temprana',
  GOOD: 'Buen pagador',
  BAD: 'Mal pagador',
  INDETERMINATE: 'Indeterminado',
  STABLE: 'Estable',
  SHIFTED: 'Desplazada',
  UNSTABLE: 'Inestable',
  GAP: 'Sin cubrir',
  IN_PROGRESS: 'En curso',
  NOT_STARTED: 'Sin empezar',
  DONE: 'Hecho',
  CLOSED: 'Cerrado',
  RESOLVED: 'Resuelto',
  UNASSIGNED: 'Sin asignar',
  EXPIRED: 'Vencido',
  OVERDUE: 'Vencido',
  ON_TIME: 'En plazo',
  BREACHED: 'Plazo incumplido',
  AT_RISK: 'En riesgo',
  ANALYZED: 'Analizado',
  CONSUMED: 'Usado',
  DISPATCHED: 'Enviado',
  EXCLUDED: 'Excluido',
  MASKED: 'Enmascarado',
  REDACTED: 'Tachado',
  LICENSED: 'Con licencia',
  OPERATIONAL: 'En operación',
  UNKNOWN: 'Desconocido',
  ENABLED: 'Encendido',
  DISABLED: 'Apagado',
  ONLINE: 'En línea',
  OFFLINE: 'Sin conexión',
  UP: 'Funcionando',
  COVERED: 'Cubierto',
  UNCOVERED: 'Sin cubrir',
  REACHED: 'Alcanzado',
  UNREACHED: 'No alcanzado',
  'SIN DATO': 'Sin dato',
};

/** Un valor sin traducción, legible: «SOME_NEW_STATE» → «Some new state». */
export function readableStatus(raw: string): string {
  const spaced = raw.replace(/_+/g, ' ').trim().toLowerCase();
  return spaced ? spaced.charAt(0).toUpperCase() + spaced.slice(1) : raw;
}

/** El texto de un estado para ponerlo dentro de una frase o de un subtítulo. */
export function statusText(raw: unknown, labels?: Record<string, string>): string {
  if (raw === null || raw === undefined || raw === '') return '—';
  const key = String(raw).toUpperCase();
  return labels?.[key] ?? STATUS_LABELS[key] ?? readableStatus(key);
}
