/**
 * Cómo se dice en pantalla cada estado que devuelve el motor.
 *
 * `StatusBadge` enseñaba el valor crudo en mayúsculas (ACTIVE, DRAFT, PASSED, WAITING…) salvo en
 * las 5 de sus 43 llamadas que pasaban su propio mapa. Éste es el mapa por defecto: una llamada con
 * `labels` propios sigue mandando, y un valor que no esté aquí se enseña legible (sin guiones
 * bajos, sólo la primera en mayúscula) en vez de como constante.
 */
export const STATUS_LABELS: Readonly<Record<string, string>> = {
  ACTIVE: 'Activo',
  INACTIVE: 'Inactivo',
  TRUE: 'Activo',
  FALSE: 'Inactivo',
  DRAFT: 'Borrador',
  DRAFT_SAVED: 'Borrador guardado',
  REVIEW: 'En revisión',
  IN_REVIEW: 'En revisión',
  PENDING: 'Pendiente',
  PENDING_REVIEW: 'Pendiente de revisión',
  WAITING: 'En espera',
  QUEUED: 'En cola',
  RUNNING: 'En curso',
  PROCESSING: 'Procesando',
  PREPARING: 'Preparando',
  GENERATING: 'Generando',
  READY: 'Listo',
  OPEN: 'Abierto',
  ASSIGNED: 'Asignado',
  RECEIVED: 'Recibido',
  REQUESTED: 'Solicitado',
  COMPLETED: 'Completado',
  COMPLETE: 'Completo',
  PARTIAL: 'Parcial',
  FULFILLED: 'Atendido',
  CONFIRMED: 'Confirmado',
  VALID: 'Válido',
  VALIDATED: 'Validado',
  INVALID: 'No válido',
  VALIDATION_FAILED: 'Falló la validación',
  COMPILED: 'Compilado',
  PUBLISHED: 'Publicado',
  DEPLOYED: 'Desplegado',
  DEPLOYED_TO_DEV: 'Desplegado en desarrollo',
  DEPLOYED_TO_TEST: 'Desplegado en pruebas',
  DEPLOYED_TO_STAGING: 'Desplegado en preproducción',
  DEPLOYED_TO_PROD: 'Desplegado en producción',
  ACTIVE_IN_ENVIRONMENT: 'Activo en el ambiente',
  SUPERSEDED: 'Reemplazado',
  ROLLED_BACK: 'Revertido',
  RETIRED: 'Retirado',
  DEPRECATED: 'En desuso',
  SUSPENDED: 'Suspendido',
  REVOKED: 'Revocado',
  BLOCKED: 'Bloqueado',
  CANCELLED: 'Cancelado',
  APPROVE: 'Aprobar',
  APPROVED: 'Aprobado',
  REJECT: 'Rechazar',
  REJECTED: 'Rechazado',
  DECLINED: 'Rechazado',
  CHANGES_REQUESTED: 'Cambios pedidos',
  REQUEST_CHANGES: 'Pedir cambios',
  MANUAL_REVIEW: 'Revisión manual',
  REVISION_MANUAL: 'Revisión manual',
  RESOLVED_APPROVED: 'Resuelto: aprobado',
  RESOLVED_DECLINED: 'Resuelto: rechazado',
  NO_DECISION: 'Sin decisión',
  PASS: 'Correcto',
  PASSED: 'Superada',
  FAIL: 'Falló',
  FAILED: 'Falló',
  FAILED_RETRYABLE: 'Falló (se reintentará)',
  FAILED_PERMANENT: 'Falló',
  SUCCESS: 'Correcto',
  SUCCEEDED: 'Correcto',
  SUCCEEDED_WITH_WARNINGS: 'Correcto con avisos',
  SKIP: 'Omitido',
  SKIPPED: 'Omitido',
  ERROR: 'Error',
  TIMEOUT: 'Tiempo agotado',
  WARN: 'Aviso',
  WARNING: 'Aviso',
  INFO: 'Informativo',
  OK: 'Correcto',
  HEALTHY: 'Funcionando',
  DEGRADED: 'Con fallas',
  DOWN: 'Caído',
  CRITICAL: 'Crítico',
  HIGH: 'Alto',
  MEDIUM: 'Medio',
  LOW: 'Bajo',
  BLOCKING: 'Obligatoria',
  NON_BLOCKING: 'Informativa',
  REQUIRED: 'Obligatorio',
  NONE: 'Ninguno',
  NOT_APPLICABLE: 'No aplica',
  PUBLIC: 'Público',
  INTERNAL: 'Interno',
  CONFIDENTIAL: 'Confidencial',
  RESTRICTED: 'Restringido',
  SECRET: 'Secreto',
  PII: 'Dato personal',
  SENSITIVE_PII: 'Dato personal sensible',
  INPUT: 'Entrada',
  OUTPUT: 'Salida',
  OUTPUT_PRIMARY: 'Salida principal',
  DIRECT: 'Completa',
  CANARY: 'Gradual',
  CHAMPION_CHALLENGER: 'Comparativa',
  WATCH: 'En observación',
  BREACH: 'Límite superado',
  EARLY_WARNING: 'Alerta temprana',
  GOOD: 'Buen pagador',
  BAD: 'Mal pagador',
  INDETERMINATE: 'Indeterminado',
  STABLE: 'Estable',
  SHIFTED: 'Desplazada',
  UNSTABLE: 'Inestable',
  GAP: 'Sin cubrir',
  IN_PROGRESS: 'En curso',
  NOT_STARTED: 'Sin empezar',
  DONE: 'Hecho',
  CLOSED: 'Cerrado',
  RESOLVED: 'Resuelto',
  UNASSIGNED: 'Sin asignar',
  EXPIRED: 'Vencido',
  ON_TIME: 'En plazo',
  BREACHED: 'Plazo incumplido',
  AT_RISK: 'En riesgo',
  ANALYZED: 'Analizado',
  CONSUMED: 'Usado',
  DISPATCHED: 'Enviado',
  EXCLUDED: 'Excluido',
  MASKED: 'Enmascarado',
  REDACTED: 'Tachado',
  LICENSED: 'Con licencia',
  OPERATIONAL: 'En operación',
  UNKNOWN: 'Desconocido',
  ENABLED: 'Encendido',
  DISABLED: 'Apagado',
  ONLINE: 'En línea',
  OFFLINE: 'Sin conexión',
  UP: 'Funcionando',
  COVERED: 'Cubierto',
  UNCOVERED: 'Sin cubrir',
  REACHED: 'Alcanzado',
  UNREACHED: 'No alcanzado',
  // Plazos de una revisión (`governance.service.ts`).
  ON_TRACK: 'En plazo',
  OVERDUE: 'Fuera de plazo',
  // Tipos de acción de un nodo (`graph-structure.validator.ts`).
  SET_OUTCOME: 'Fija el resultado',
  SET_SCORE: 'Fija el puntaje',
  ADD_SCORE: 'Suma puntaje',
  SET_LIMIT: 'Fija el límite',
  SET_RISK_BAND: 'Fija la banda de riesgo',
  SET_FIELD: 'Asigna un valor',
  CREATE_MANUAL_REVIEW: 'Envía a revisión manual',
  EMIT_REASON: 'Emite un motivo',
  // Ambientes.
  DEV: 'Desarrollo',
  DEVELOPMENT: 'Desarrollo',
  TEST: 'Pruebas',
  QA: 'Pruebas',
  SANDBOX: 'Pruebas aisladas',
  STAGING: 'Preproducción',
  PROD: 'Producción',
  PRODUCTION: 'Producción',
  // Modos de despliegue y flujos de aprobación.
  FULL: 'Completo',
  STANDARD: 'Estándar',
  EXPEDITED: 'Urgente',
  // Tipos y dominios de los algoritmos, y categorías de motivos.
  CREDIT_UNDERWRITING: 'Aprobación de crédito',
  RISK_POLICY: 'Política de riesgo',
  IDENTITY_POLICY: 'Política de identidad',
  FRAUD_POLICY: 'Política de fraude',
  PRICING_POLICY: 'Política de precio',
  RISK_DECISIONING: 'Decisiones de riesgo',
  MERCHANT_RISK: 'Riesgo de comercios',
  ONBOARDING_RISK: 'Riesgo de alta',
  CREDIT: 'Crédito',
  FRAUD: 'Fraude',
  KYC: 'Identidad',
  KYB: 'Identidad del comercio',
  COMPLIANCE: 'Cumplimiento',
  // Origen de una variable.
  REQUEST_PAYLOAD: 'Datos de la solicitud',
  DECISION_ENGINE: 'Lo calcula el motor',
  // Eventos de la bitácora.
  APPROVAL_REQUEST_CREATED: 'Solicitud de aprobación creada',
  APPROVAL_APPROVE: 'Aprobación firmada',
  APPROVAL_REJECT: 'Aprobación rechazada',
  APPROVED_LIBRARY_UPSERTED: 'Librería autorizada guardada',
  ARTIFACT_COMPILED: 'Algoritmo compilado',
  ARTIFACT_CREATED: 'Algoritmo creado',
  ARTIFACT_REFERENCE_CREATED: 'Referencia entre algoritmos creada',
  ARTIFACT_REFERENCE_DELETED: 'Referencia entre algoritmos borrada',
  ARTIFACT_REFERENCE_UPDATED: 'Referencia entre algoritmos cambiada',
  ARTIFACT_VERSION_CLONED: 'Versión copiada',
  ARTIFACT_VERSION_NOTES_UPDATED: 'Notas de la versión cambiadas',
  ARTIFACT_VERSION_PROCESSING_BASIS_UPDATED: 'Base legal de la versión cambiada',
  BANK_STATEMENT_REVIEW_CLAIMED: 'Extracto tomado para revisar',
  BANK_STATEMENT_REVIEW_REPROCESSED: 'Extracto reprocesado',
  BANK_STATEMENT_REVIEW_RESOLVED: 'Revisión de extracto resuelta',
  BUSINESS_OBJECTIVE_CREATED: 'Objetivo de negocio creado',
  CALCULATED_FIELD_CREATED: 'Campo calculado creado',
  CALCULATED_FIELD_VERSION_CREATED: 'Versión de campo calculado creada',
  CALCULATED_FIELD_VERSION_PROMOTED: 'Versión de campo calculado activada',
  CODE_IMPORT_ANALYZED: 'Código importado analizado',
  CODE_IMPORT_CANCELLED: 'Importación de código cancelada',
  CREDIT_FACILITIES_REGISTERED: 'Créditos concedidos registrados',
  DATA_SUBJECT_REQUEST_RECEIVED: 'Solicitud del titular recibida',
  DECISION_EXECUTED: 'Decisión tomada',
  DECISION_FAILED: 'Decisión fallida',
  DECISION_NO_DECISION_ECONOMIC_OUTPUT: 'Sin decisión: falta la salida económica',
  DECISION_NO_DECISION_ENABLING_BASIS: 'Sin decisión: falta la base legal',
  DECISION_NO_DECISION_VARIABLES: 'Sin decisión: faltan datos',
  DEPLOYMENT_ACTIVATED: 'Despliegue activado',
  DEPLOYMENT_ROLLED_BACK: 'Despliegue revertido',
  DEPLOYMENT_SUSPENDED: 'Despliegue suspendido',
  EXPOSURE_LIMIT_UPSERTED: 'Límite de exposición guardado',
  IDENTITY_REVIEW_CLAIMED: 'Revisión de identidad tomada',
  IDENTITY_REVIEW_RESOLVED: 'Revisión de identidad resuelta',
  MANUAL_REVIEW_ASSIGNED: 'Caso asignado',
  MANUAL_REVIEW_CALLBACK_FAILED: 'No se pudo avisar el resultado del caso',
  MANUAL_REVIEW_DOSSIER_ATTACHED: 'Expediente adjuntado al caso',
  MANUAL_REVIEW_OPENED: 'Caso abierto',
  MANUAL_REVIEW_RESOLVED: 'Caso resuelto',
  MODEL_DOSSIER_RECORDED: 'Expediente del modelo registrado',
  MODEL_MONITORING_ATTRIBUTES_RECORDED: 'Atributos de monitoreo registrados',
  MODEL_OUTCOMES_RECORDED: 'Desenlaces registrados',
  POLICY_ARTIFACT_LINKED: 'Algoritmo vinculado a una política',
  POLICY_TEST_LINKED: 'Prueba vinculada a una política',
  QA_GENERATION_RUN_COMPLETED: 'Generación de casos terminada',
  REASON_CODE_CREATED: 'Motivo creado',
  REIDENTIFICATION_REQUESTED: 'Reidentificación pedida',
  RULE_GRAPH_REPLACED: 'Diagrama de reglas reemplazado',
  SEMANTIC_MODEL_SETTINGS_RESET: 'Ajustes del modelo semántico restablecidos',
  SEMANTIC_MODEL_SETTINGS_UPDATED: 'Ajustes del modelo semántico cambiados',
  SUBJECT_CONSENT_RECORDED: 'Consentimiento registrado',
  SUBJECT_CONSENT_REVOKED: 'Consentimiento revocado',
  TEST_CASES_ADDED: 'Casos de prueba añadidos',
  TEST_RUN_QUEUED: 'Corrida de pruebas en cola',
  TEST_RUN_PASSED: 'Corrida de pruebas superada',
  TEST_RUN_FAILED: 'Corrida de pruebas fallida',
  TEST_SUITE_CREATED: 'Suite de pruebas creada',
  VALIDATION_PASSED: 'Validación superada',
  VARIABLE_DEFINITION_CREATED: 'Variable creada',
  VARIABLE_VERSION_CREATED: 'Versión de variable creada',
  'SIN DATO': 'Sin dato',
};

/** Un valor sin traducción, legible: «SOME_NEW_STATE» → «Some new state». */
export function readableStatus(raw: string): string {
  const spaced = raw.replace(/_+/g, ' ').trim().toLowerCase();
  return spaced ? spaced.charAt(0).toUpperCase() + spaced.slice(1) : raw;
}

/** El texto de un estado para ponerlo dentro de una frase o de un subtítulo. */
export function statusText(raw: unknown, labels?: Record<string, string>): string {
  if (raw === null || raw === undefined || raw === '') return '—';
  const key = String(raw).toUpperCase();
  return labels?.[key] ?? STATUS_LABELS[key] ?? readableStatus(key);
}

/**
 * El texto de un CÓDIGO de catálogo (tipo, origen, ambiente, evento…) dentro de una tabla.
 * A diferencia de `statusText`, un código sin traducción se enseña tal cual y no «legible»:
 * pasar `CUSTOM_SEGMENT_A` a «Custom segment a» inventaría una palabra que nadie usa.
 */
export function codeText(raw: unknown, labels?: Record<string, string>): string {
  if (raw === null || raw === undefined || raw === '') return '—';
  const code = String(raw);
  return (
    labels?.[code] ?? labels?.[code.toUpperCase()] ?? STATUS_LABELS[code.toUpperCase()] ?? code
  );
}

/** Quién actuó cuando no fue una persona: las cuentas técnicas con las que el motor se carga solo. */
export const SYSTEM_ACTOR_LABELS: Readonly<Record<string, string>> = {
  'bootstrap-management': 'Sistema (carga inicial)',
  'seed.system': 'Sistema (carga inicial)',
  system: 'Sistema',
};
